### ISSUE TITLE
[FEAT] 대시보드 - 포인트 사용 내역

### ISSUE THREAD

**Issue by tigris24** [Kernel360/F2-BIENGUAL-BE#375]
# [FEAT] 대시보드 - 포인트 사용 내역
## 포인트 사용 내역 저장
- [ ] 기존 PointHistoryEntity 삭제
- [ ] 새로운 PointHistoryEntity 구성
    - [ ] 포인트 대시보드 관련 Spring Batch 수정
    - [ ] Content 히스토리
    - [ ] Question 히스토리
    - [ ] Daily Mission 히스토리

**Comment by mooncw** [comment]
#384 이슈 확인해주세요.
